package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DO1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.DO2 do2;

	public DO1() {
	}

	public com.DO2 getDo2() {
		return this.do2;
	}

	public void setDo2(com.DO2 do2) {
		this.do2 = do2;
	}

	public DO1(com.DO2 do2) {
		this.do2 = do2;
	}

}