package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DO1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.DO2 do2;

	private java.lang.String name;

	public DO1() {
	}

	public com.DO2 getDo2() {
		return this.do2;
	}

	public void setDo2(com.DO2 do2) {
		this.do2 = do2;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public DO1(com.DO2 do2, java.lang.String name) {
		this.do2 = do2;
		this.name = name;
	}

}